import Head from "next/head";
import NavBar from "./NavBar";
import Footer from "./Footer";
import Callback from "./Callback";
import CallbackForm from "./CallbackForm";
import { useEffect, useState } from "react";

export function MainLayout({ children, title }) {
  const [callBackFormOnClose, setCallBackFormOnClose] = useState(false); // Callback form On or Close

  const triggerToggleForm = () => {
    setCallBackFormOnClose(!callBackFormOnClose);
  };

  return (
    <div className="wrapper">
      <Head>
        <title>{title} | Alin</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar triggerToggleForm={triggerToggleForm} />

      {callBackFormOnClose ? (
        <CallbackForm triggerToggleForm={triggerToggleForm} />
      ) : null}

      <main className="text-gray-700 mt-24">{children}</main>

      <Callback />

      <Footer />
    </div>
  );
}
